version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "DeckProject123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  webapi:
    build: .
    container_name: cart-app
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=DeckCartDb;User Id=sa;Password=DeckProject123!;TrustServerCertificate=True;
      - JwtConfig__Secret=MySuperLongSecureJwtSecretKey_1234567890!
      - JwtConfig__Issuer=DeckApi
      - JwtConfig__Audience=DeckApiUsers
    ports:
      - "5000:8080"
    networks:
      - app-network

volumes:
  sql_data:

networks:
  app-network: